version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: minibuddy
      POSTGRES_PASSWORD: minibuddy
      POSTGRES_DB: minibuddy_db
    ports:
      - "5432:5432"
