spring:
  application:
    name: minibuddy
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://db:5432/minibuddy_db}
    username: ${DB_USERNAME:minibuddy}
    password: ${DB_PASSWORD:minibuddy}
  flyway:
    url: ${DB_URL:jdbc:postgresql://db:5432/minibuddy_db}
    user: ${DB_USER:minibuddy}
    password: ${DB_PASSWORD:minibuddy}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: ${SERVER_PORT:8080}

app:
  storage:
    basePath: audio_storage

logging:
  level:
    com.example.minibuddy: INFO
    org.springframework.web: INFO
